apiVersion: v2
name: nebari-data-science-pack
description: A Helm chart for deploying JupyterHub with jhub-apps on Kubernetes
type: application
version: 0.1.0-alpha.8
appVersion: "1.0.0"

dependencies:
  - name: jupyterhub
    version: 4.3.2
    repository: https://hub.jupyter.org/helm-chart/
