apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nebari-data-science-pack.name" . }}-hub-config
  labels:
    {{- include "nebari-data-science-pack.labels" . | nindent 4 }}
data:
  00-gateway-auth.py: |
{{ .Files.Get "config/jupyterhub/00-gateway-auth.py" | indent 4 }}
  01-spawner.py: |
{{ .Files.Get "config/jupyterhub/01-spawner.py" | replace "__SINGLEUSER_CONFIG_CM__" (printf "%s-singleuser-config" (include "nebari-data-science-pack.name" .)) | indent 4 }}
  02-jhub-apps.py: |
{{ .Files.Get "config/jupyterhub/02-jhub-apps.py" | indent 4 }}
  03-nebi-envs.py: |
{{ .Files.Get "config/jupyterhub/03-nebi-envs.py" | indent 4 }}
