apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nebi-workspaces
  labels:
    {{- include "nebari-data-science-pack.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.nebi.workspacesStorage.accessModes | nindent 4 }}
  {{- if .Values.nebi.workspacesStorage.storageClass }}
  storageClassName: {{ .Values.nebi.workspacesStorage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nebi.workspacesStorage.size }}
